    CREATE TABLE post (
      id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      text TEXT NOT NULL,
      link VARCHAR(100) UNIQUE NOT NULL,
      created TIMESTAMP NOT NULL
);